"use client";

import React, { useState } from "react";
import type { Media } from "@/payload-types";
import { cn } from "@/utilities/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import {
  MapPin,
  Phone,
  Mail,
  Clock,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  Send,
  CheckCircle,
} from "lucide-react";
import { Media as MediaComponent } from "@/components/Media";

// Types will be generated by Payload
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Props = any;

const socialIcons = {
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  youtube: Youtube,
};

const bgClasses: Record<string, string> = {
  white: "bg-white",
  muted: "bg-muted/30",
  primary: "bg-primary/5",
};

export const ContactBlock: React.FC<Props> = ({
  title,
  subtitle,
  layout = "split",
  offices,
  formSettings,
  socialLinks,
  backgroundColor = "white",
}) => {
  const [formState, setFormState] = useState({
    name: "",
    email: "",
    phone: "",
    subject: "",
    message: "",
    organization: "",
  });
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const bgClass = bgClasses[backgroundColor] || "bg-white";

  const showForm = formSettings?.showForm !== false && layout !== "addressesOnly";
  const showAddresses = layout !== "formOnly";
  const formFields = formSettings?.fields || ["name", "email", "subject", "message"];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    // Simulate form submission
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsSubmitting(false);
    setIsSubmitted(true);
  };

  const handleInputChange = (field: string, value: string) => {
    setFormState((prev) => ({ ...prev, [field]: value }));
  };

  if (!showAddresses && !showForm) return null;

  return (
    <section className={cn("py-16 md:py-24", bgClass)}>
      <div className="container px-4">
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            {title || "Get in Touch"}
          </h2>
          {subtitle && <p className="text-lg text-muted-foreground">{subtitle}</p>}
        </div>

        <div
          className={cn(
            "grid gap-8 lg:gap-12",
            layout === "split" ? "lg:grid-cols-2" : "grid-cols-1 max-w-3xl mx-auto"
          )}
        >
          {/* Office Addresses */}
          {showAddresses && offices && offices.length > 0 && (
            <div className="space-y-6">
              {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
              {offices.map((office: any, index: number) => (
                <Card key={index} className="overflow-hidden">
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      {office.flag && typeof office.flag === "object" && (
                        <div className="relative w-12 h-8 shrink-0 overflow-hidden rounded">
                          <MediaComponent
                            resource={office.flag as Media}
                            fill
                            imgClassName="object-cover"
                          />
                        </div>
                      )}
                      <div className="flex-1">
                        <h3 className="text-lg font-semibold text-foreground mb-3">
                          {office.country}
                        </h3>

                        <div className="space-y-2 text-sm">
                          {office.address && (
                            <div className="flex items-start gap-2 text-muted-foreground">
                              <MapPin className="w-4 h-4 shrink-0 mt-0.5" />
                              <span>{office.address}</span>
                            </div>
                          )}
                          {office.phone && (
                            <div className="flex items-center gap-2 text-muted-foreground">
                              <Phone className="w-4 h-4 shrink-0" />
                              <a
                                href={`tel:${office.phone}`}
                                className="hover:text-primary transition-colors"
                              >
                                {office.phone}
                              </a>
                            </div>
                          )}
                          {office.email && (
                            <div className="flex items-center gap-2 text-muted-foreground">
                              <Mail className="w-4 h-4 shrink-0" />
                              <a
                                href={`mailto:${office.email}`}
                                className="hover:text-primary transition-colors"
                              >
                                {office.email}
                              </a>
                            </div>
                          )}
                          {office.officeHours && (
                            <div className="flex items-center gap-2 text-muted-foreground">
                              <Clock className="w-4 h-4 shrink-0" />
                              <span>{office.officeHours}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Map */}
                    {office.mapUrl && (
                      <div className="mt-4 pt-4 border-t">
                        <iframe
                          src={office.mapUrl}
                          width="100%"
                          height="200"
                          style={{ border: 0, borderRadius: "8px" }}
                          allowFullScreen
                          loading="lazy"
                          referrerPolicy="no-referrer-when-downgrade"
                          title={`Map of ${office.country}`}
                        />
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}

              {/* Social Links */}
              {socialLinks && socialLinks.length > 0 && (
                <div className="pt-4">
                  <p className="text-sm font-medium text-foreground mb-3">Follow Us</p>
                  <div className="flex gap-3">
                    {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                    {socialLinks.map((link: any, index: number) => {
                      const Icon = socialIcons[link.platform as keyof typeof socialIcons];
                      if (!Icon || !link.url) return null;
                      return (
                        <a
                          key={index}
                          href={link.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary hover:bg-primary hover:text-white transition-all duration-200"
                        >
                          <Icon className="w-5 h-5" />
                        </a>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Contact Form */}
          {showForm && (
            <div>
              <Card>
                <CardContent className="p-6 md:p-8">
                  {isSubmitted ? (
                    <div className="text-center py-8">
                      <CheckCircle className="w-16 h-16 text-green-500 mx-auto mb-4" />
                      <h3 className="text-xl font-semibold text-foreground mb-2">Message Sent!</h3>
                      <p className="text-muted-foreground">
                        {formSettings?.successMessage ||
                          "Thank you! Your message has been sent successfully."}
                      </p>
                      <Button
                        variant="outline"
                        className="mt-6"
                        onClick={() => {
                          setIsSubmitted(false);
                          setFormState({
                            name: "",
                            email: "",
                            phone: "",
                            subject: "",
                            message: "",
                            organization: "",
                          });
                        }}
                      >
                        Send Another Message
                      </Button>
                    </div>
                  ) : (
                    <form onSubmit={handleSubmit} className="space-y-5">
                      <h3 className="text-xl font-semibold text-foreground mb-6">
                        {formSettings?.formTitle || "Send us a Message"}
                      </h3>

                      {formFields.includes("name") && (
                        <div className="space-y-2">
                          <Label htmlFor="name">Full Name</Label>
                          <Input
                            id="name"
                            value={formState.name}
                            onChange={(e) => handleInputChange("name", e.target.value)}
                            placeholder="Your name"
                            required
                          />
                        </div>
                      )}

                      {formFields.includes("organization") && (
                        <div className="space-y-2">
                          <Label htmlFor="organization">Organization</Label>
                          <Input
                            id="organization"
                            value={formState.organization}
                            onChange={(e) => handleInputChange("organization", e.target.value)}
                            placeholder="Your organization (optional)"
                          />
                        </div>
                      )}

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {formFields.includes("email") && (
                          <div className="space-y-2">
                            <Label htmlFor="email">Email</Label>
                            <Input
                              id="email"
                              type="email"
                              value={formState.email}
                              onChange={(e) => handleInputChange("email", e.target.value)}
                              placeholder="your@email.com"
                              required
                            />
                          </div>
                        )}

                        {formFields.includes("phone") && (
                          <div className="space-y-2">
                            <Label htmlFor="phone">Phone</Label>
                            <Input
                              id="phone"
                              type="tel"
                              value={formState.phone}
                              onChange={(e) => handleInputChange("phone", e.target.value)}
                              placeholder="+977 98XXXXXXXX"
                            />
                          </div>
                        )}
                      </div>

                      {formFields.includes("subject") && (
                        <div className="space-y-2">
                          <Label htmlFor="subject">Subject</Label>
                          <Input
                            id="subject"
                            value={formState.subject}
                            onChange={(e) => handleInputChange("subject", e.target.value)}
                            placeholder="What is this regarding?"
                            required
                          />
                        </div>
                      )}

                      {formFields.includes("message") && (
                        <div className="space-y-2">
                          <Label htmlFor="message">Message</Label>
                          <Textarea
                            id="message"
                            value={formState.message}
                            onChange={(e) => handleInputChange("message", e.target.value)}
                            placeholder="Your message..."
                            rows={5}
                            required
                          />
                        </div>
                      )}

                      <Button type="submit" className="w-full" disabled={isSubmitting}>
                        {isSubmitting ? (
                          "Sending..."
                        ) : (
                          <>
                            <Send className="w-4 h-4 mr-2" />
                            {formSettings?.submitButtonText || "Send Message"}
                          </>
                        )}
                      </Button>
                    </form>
                  )}
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </div>
    </section>
  );
};
