import type { Block } from "payload";

export const MoodQuiz: Block = {
  slug: "moodQuiz",
  interfaceName: "MoodQuizBlock",
  imageURL: "/blocks-preview/moodQuiz.webp",
  labels: {
    singular: "Mood Quiz",
    plural: "Mood Quizzes",
  },
  fields: [
    {
      name: "isEnabled",
      type: "checkbox",
      defaultValue: true,
      label: "Enable this block",
    },
    {
      name: "sectionLabel",
      type: "text",
      label: "Section Label (above heading)",
      defaultValue: "Mood Quiz",
      localized: true,
    },
    {
      name: "heading",
      type: "text",
      label: "Heading",
      defaultValue: "Find Your Perfect Color",
      required: true,
      localized: true,
    },
    {
      name: "subheading",
      type: "text",
      label: "Subheading",
      defaultValue: "Answer 3 quick questions and we'll suggest your ideal palette.",
      localized: true,
    },
    {
      name: "moods",
      type: "array",
      label: "Moods (Step 1)",
      minRows: 2,
      maxRows: 8,
      admin: {
        description:
          "Each mood maps to colors from the Colors collection (via Mood Tag). Swatch colors are for the preview dots only.",
      },
      fields: [
        {
          name: "label",
          type: "text",
          label: "Mood Label (e.g. Calm)",
          required: true,
          localized: true,
        },
        {
          name: "icon",
          type: "select",
          label: "Icon",
          required: true,
          options: [
            { label: "Waves (Calm)", value: "Waves" },
            { label: "Flame (Bold)", value: "Flame" },
            { label: "Sun (Warm)", value: "Sun" },
            { label: "Leaf (Fresh)", value: "Leaf" },
            { label: "Star", value: "Star" },
            { label: "Heart", value: "Heart" },
            { label: "Zap (Energy)", value: "Zap" },
            { label: "Cloud", value: "Cloud" },
          ],
          defaultValue: "Waves",
        },
        {
          name: "moodTag",
          type: "select",
          label: "Mood Tag (links to Colors collection)",
          required: true,
          admin: {
            description:
              "Colors tagged with this mood will be shown as results after the user picks this mood.",
          },
          options: [
            { label: "Calm", value: "calm" },
            { label: "Vibrant", value: "vibrant" },
            { label: "Earthy", value: "earthy" },
            { label: "Energetic", value: "energetic" },
            { label: "Elegant", value: "elegant" },
            { label: "Playful", value: "playful" },
            { label: "Minimalist", value: "minimalist" },
            { label: "Cozy", value: "cozy" },
          ],
          defaultValue: "calm",
        },
        {
          name: "swatchColors",
          type: "array",
          label: "Swatch Preview Colors (shown on mood card — 3 recommended)",
          minRows: 1,
          maxRows: 5,
          admin: {
            description: "Quick preview swatches displayed on the mood button. Use hex codes.",
          },
          fields: [
            {
              name: "hex",
              type: "text",
              label: "Hex Code (e.g. #A8C4D4)",
              required: true,
            },
          ],
        },
      ],
    },
    {
      name: "roomTypes",
      type: "array",
      label: "Room Types (Step 2)",
      minRows: 2,
      maxRows: 12,
      fields: [
        {
          name: "label",
          type: "text",
          label: "Room Label (e.g. Living Room)",
          required: true,
          localized: true,
        },
        {
          name: "icon",
          type: "select",
          label: "Icon",
          required: true,
          options: [
            { label: "Sofa (Living Room)", value: "Sofa" },
            { label: "Bed (Bedroom)", value: "BedDouble" },
            { label: "Chef Hat (Kitchen)", value: "ChefHat" },
            { label: "Shower (Bathroom)", value: "ShowerHead" },
            { label: "Book (Study)", value: "BookOpen" },
            { label: "Home (Exterior)", value: "Home" },
            { label: "Baby", value: "Baby" },
            { label: "Dumbbell (Gym)", value: "Dumbbell" },
          ],
          defaultValue: "Home",
        },
      ],
    },
    {
      name: "maxResultColors",
      type: "number",
      label: "Max Result Colors per Mood",
      defaultValue: 6,
      min: 1,
      max: 12,
      admin: {
        description: "How many colors from the database to show after the quiz. Sorted by popularity.",
      },
    },
    {
      name: "step1Label",
      type: "text",
      label: "Step 1 — Question",
      defaultValue: "Pick a Mood",
      localized: true,
    },
    {
      name: "step1Sub",
      type: "text",
      label: "Step 1 — Sub Text",
      defaultValue: "How do you want your space to feel?",
      localized: true,
    },
    {
      name: "step2Label",
      type: "text",
      label: "Step 2 — Question",
      defaultValue: "Pick a Room Type",
      localized: true,
    },
    {
      name: "step2Sub",
      type: "text",
      label: "Step 2 — Sub Text",
      defaultValue: "Which room are you painting?",
      localized: true,
    },
    {
      name: "step3Label",
      type: "text",
      label: "Step 3 — Question",
      defaultValue: "Light Level",
      localized: true,
    },
    {
      name: "step3Sub",
      type: "text",
      label: "Step 3 — Sub Text",
      defaultValue: "How much natural light does your room get?",
      localized: true,
    },
    {
      name: "resultsLabel",
      type: "text",
      label: "Results Label",
      defaultValue: "Your Recommended Colors",
      localized: true,
    },
    {
      name: "orderSampleLabel",
      type: "text",
      label: "Order Sample Button Label",
      defaultValue: "Order Sample",
      localized: true,
    },
  ],
};
