/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    portfolio: Portfolio;
    films: Film;
    services: Service;
    albums: Album;
    'contact-submissions': ContactSubmission;
    testimonials: Testimonial;
    media: Media;
    files: File;
    pages: Page;
    posts: Post;
    categories: Category;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    redirects: Redirect;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    films: FilmsSelect<false> | FilmsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ne' | 'hi' | 'zh' | 'fr' | 'it' | 'ko' | 'ru' | 'hr')
    | ('en' | 'ne' | 'hi' | 'zh' | 'fr' | 'it' | 'ko' | 'ru' | 'hr')[];
  globals: {
    'studio-settings': StudioSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'studio-settings': StudioSettingsSelect<false> | StudioSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ne' | 'hi' | 'zh' | 'fr' | 'it' | 'ko' | 'ru' | 'hr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: string;
  title: string;
  category: 'weddings' | 'events' | 'fashion' | 'concerts' | 'commercial';
  /**
   * Upload local/media asset image
   */
  image?: (string | null) | Media;
  /**
   * Optional fallback or external CDN/Unsplash URL if not uploading media
   */
  imageUrl?: string | null;
  /**
   * Shoot location (e.g. Kathmandu, Pokhara, Bhaktapur, Patan)
   */
  location?: string | null;
  /**
   * Client or couple name (optional)
   */
  client?: string | null;
  /**
   * Feature this item on the studio homepage preview
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first (e.g. 1, 2, 3...)
   */
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films".
 */
export interface Film {
  id: string;
  title: string;
  category: 'Wedding Film' | 'Cinematic Reel' | 'Event Aftermovie' | 'Concert Film' | 'Commercial' | 'Music Video';
  /**
   * YouTube / Vimeo embed or video URL (e.g. https://www.youtube-nocookie.com/embed/...)
   */
  videoUrl: string;
  /**
   * Poster image uploaded to media
   */
  posterImage?: (string | null) | Media;
  /**
   * Fallback direct CDN or external poster URL
   */
  posterUrl?: string | null;
  /**
   * Film duration display (e.g. 4:32, 6:05)
   */
  duration?: string | null;
  /**
   * Show in homepage films reel
   */
  featured?: boolean | null;
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * 3-digit prefix number (e.g. 001, 002, 003...)
   */
  serviceNumber: string;
  /**
   * Catchy single-sentence proposition (e.g. 'Cinema-grade media for civic leaders.')
   */
  tagline?: string | null;
  /**
   * Brief summary used in cards on homepage and services archive
   */
  shortDescription: string;
  /**
   * Primary high-resolution hero photo for the single service page
   */
  heroImage?: (string | null) | Media;
  /**
   * External CDN/Unsplash image fallback URL if not uploading media
   */
  heroImageUrl?: string | null;
  /**
   * Detailed narrative explaining why clients commission this service
   */
  overview?: string | null;
  /**
   * Primary audience (e.g. 'Mayors, Civic Leaders, Celebrities, VIP Figures')
   */
  targetAudience?: string | null;
  /**
   * Notice displayed on VIP service pages (e.g. NDA / discretion guarantee)
   */
  confidentialityNotice?: string | null;
  deliverables?:
    | {
        title: string;
        description: string;
        /**
         * Optional badge tag (e.g. '4K HDR', 'Same-Day Press', 'NDA Protected')
         */
        highlight?: string | null;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        stepNumber?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  icon?:
    | (
        | 'camera'
        | 'film'
        | 'compass'
        | 'party'
        | 'music'
        | 'video'
        | 'smartphone'
        | 'sparkles'
        | 'tv'
        | 'lightbulb'
        | 'award'
        | 'star'
      )
    | null;
  featured?: boolean | null;
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: string;
  title: string;
  featuredImage: string | Media;
  images: {
    image: string | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  service?: ('wedding' | 'videography' | 'drone' | 'fashion' | 'concert' | 'brand' | 'other') | null;
  message: string;
  /**
   * Where this inquiry was submitted from
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  clientName: string;
  /**
   * Client role and location (e.g. Bride · Kathmandu, Brand Director)
   */
  roleOrEvent: string;
  quote: string;
  rating?: number | null;
  avatar?: (string | null) | Media;
  /**
   * Fallback avatar image URL
   */
  avatarUrl?: string | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Central file storage — notices, PDFs, form attachments, staff documents, certificates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  /**
   * Private files are only accessible to admins and staff. Sensitive categories are auto-set to private.
   */
  isPrivate?: boolean | null;
  fileCategory:
    | 'notice_pdf'
    | 'notice_image'
    | 'staff_photo'
    | 'report'
    | 'tender'
    | 'form_attachment'
    | 'academic_certificate'
    | 'identity_document'
    | 'authorization_letter'
    | 'staff_contract'
    | 'cv'
    | 'warranty_invoice'
    | 'other';
  uploadedFrom?:
    | (
        | 'admin'
        | 'notices'
        | 'suchi-darta'
        | 'common-form-submissions'
        | 'grievance-complaints'
        | 'staffs'
        | 'careers'
        | 'talent-network'
      )
    | null;
  uploadedBy?: (string | null) | User;
  title: string;
  description?: string | null;
  /**
   * e.g. 2081/2082
   */
  fiscalYear?: string | null;
  expiryDate?: string | null;
  /**
   * e.g. SDC-A3KF92PQ
   */
  relatedTrackingCode?: string | null;
  isVerified?: boolean | null;
  verifiedBy?: (string | null) | User;
  verificationNotes?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'staff' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type:
      | 'none'
      | 'studioHero'
      | 'highImpact'
      | 'mediumImpact'
      | 'lowImpact'
      | 'missionHero'
      | 'statsHero'
      | 'splitHero'
      | 'videoHero'
      | 'storyHero'
      | 'minimalHero';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            image?: (string | null) | Media;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    splitLayout?: ('left' | 'right') | null;
    /**
     * Direct URL to MP4 video file
     */
    videoUrl?: string | null;
    videoPoster?: (string | null) | Media;
    storyQuote?: string | null;
    storyAuthor?: string | null;
    storyAuthorTitle?: string | null;
    storyAuthorImage?: (string | null) | Media;
  };
  layout?:
    | (
        | StudioHeroBlock
        | {
            /**
             * Text shown after 'Home >' (e.g. Portfolio)
             */
            breadcrumb?: string | null;
            eyebrow?: string | null;
            title?: string | null;
            highlight?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioPageHeader';
          }
        | StudioMarqueeBlock
        | StudioPortfolioBlock
        | StudioFilmsBlock
        | StudioServicesBlock
        | StudioStoryBlock
        | StudioStatsBlock
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlight?: string | null;
            items?:
              | {
                  title: string;
                  desc: string;
                  iconType?: ('sparkles' | 'heart' | 'video' | 'shield') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioPillars';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlight?: string | null;
            description?: string | null;
            steps?:
              | {
                  stepNumber: string;
                  tag: string;
                  title: string;
                  description: string;
                  iconType?: ('compass' | 'camera' | 'sliders' | 'sparkles') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioProcess';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlight?: string | null;
            description?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioJournal';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlight?: string | null;
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioFAQ';
          }
        | StudioTestimonialsBlock
        | StudioSocialBlock
        | {
            eyebrow?: string | null;
            heading?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'studioBanner';
          }
        | StudioContactBlock
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | GalleryBlock
        | BrandMarqueeBlock
        | CarouselBlock
        | TestimonialsBlock
        | ContactBlock
        | AboutUsBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Mandatory featured/hero image for the blog post and preview cards.
   */
  heroImage: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * Optional sorting order. Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioHeroBlock".
 */
export interface StudioHeroBlock {
  eyebrow?: string | null;
  headlinePart1?: string | null;
  headlinePart2?: string | null;
  subheadline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioMarqueeBlock".
 */
export interface StudioMarqueeBlock {
  overrideItems?: boolean | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioPortfolioBlock".
 */
export interface StudioPortfolioBlock {
  /**
   * When checked, shows the top 9 items with category filters and a 'View Full Portfolio' CTA button.
   */
  isHomepagePreview?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioPortfolio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioFilmsBlock".
 */
export interface StudioFilmsBlock {
  /**
   * Enables slider carousel mode with preview badges.
   */
  isHomepagePreview?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioFilms';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioServicesBlock".
 */
export interface StudioServicesBlock {
  /**
   * Shows the top 6 core disciplines with luxury glow cards and direct booking links.
   */
  isHomepagePreview?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioServices';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioStoryBlock".
 */
export interface StudioStoryBlock {
  /**
   * Leave empty to use default from Studio Settings.
   */
  headline?: string | null;
  /**
   * Leave empty to use default from Studio Settings.
   */
  quote?: string | null;
  /**
   * Leave empty to use default from Studio Settings.
   */
  paragraph1?: string | null;
  /**
   * Leave empty to use default from Studio Settings.
   */
  paragraph2?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioStatsBlock".
 */
export interface StudioStatsBlock {
  overrideStats?: boolean | null;
  projectsCount?: number | null;
  clientsCount?: number | null;
  socialReach?: string | null;
  yearsExperience?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioTestimonialsBlock".
 */
export interface StudioTestimonialsBlock {
  title?: string | null;
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioTestimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioSocialBlock".
 */
export interface StudioSocialBlock {
  instagramHandle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioSocial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioContactBlock".
 */
export interface StudioContactBlock {
  heading?: string | null;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'studioContact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          image?: (string | null) | Media;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          image?: (string | null) | Media;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  caption?: string | null;
  columns?: ('2' | '3' | '4') | null;
  images?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandMarqueeBlock".
 */
export interface BrandMarqueeBlock {
  title?: string | null;
  brands?:
    | {
        /**
         * Used for accessibility and reference
         */
        name?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  slides: {
    image: string | Media;
    title?: string | null;
    subtitle?: string | null;
    link?: {
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
    };
    id?: string | null;
  }[];
  height?: ('sm' | 'md' | 'lg' | 'full') | null;
  aspectRatio?: ('none' | '16/9' | '4/3' | '1/1') | null;
  loop?: boolean | null;
  autoplay?: boolean | null;
  autoplayDelay?: number | null;
  showArrows?: boolean | null;
  showDots?: boolean | null;
  showOverlay?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carouselBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  title?: string | null;
  subtitle?: string | null;
  testimonials?:
    | {
        type?: ('beneficiary' | 'donor' | 'volunteer' | 'partner') | null;
        quote: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        authorName: string;
        authorTitle?: string | null;
        authorImage?: (string | null) | Media;
        location?: string | null;
        featuredImage?: (string | null) | Media;
        /**
         * YouTube or Vimeo URL for video testimonials
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('carousel' | 'grid' | 'masonry') | null;
  showTypeFilter?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  title?: string | null;
  subtitle?: string | null;
  layout?: ('split' | 'formOnly' | 'addressesOnly') | null;
  offices?:
    | {
        country: string;
        address: string;
        phone?: string | null;
        email?: string | null;
        officeHours?: string | null;
        mapUrl?: string | null;
        flag?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  formSettings?: {
    showForm?: boolean | null;
    formTitle?: string | null;
    submitButtonText?: string | null;
    successMessage?: string | null;
    /**
     * Where contact form submissions should be sent
     */
    recipientEmail?: string | null;
    fields?: ('name' | 'email' | 'phone' | 'subject' | 'message' | 'organization')[] | null;
  };
  socialLinks?:
    | {
        platform?: ('facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  backgroundColor?: ('white' | 'muted' | 'primary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsBlock".
 */
export interface AboutUsBlock {
  isVisibleOnHomepage?: boolean | null;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  historyTitle?: string | null;
  historyTimeline?:
    | {
        year: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  showFacebookIframe?: boolean | null;
  facebookPageUrl?: string | null;
  iframePosition?: ('right' | 'left') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: string | Post;
      }
    | {
        relationTo: 'pages';
        value: string | Page;
      }
    | {
        relationTo: 'portfolio';
        value: string | Portfolio;
      }
    | {
        relationTo: 'services';
        value: string | Service;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  portfolio?: {
    /**
     * Allow clients to find portfolio.
     */
    find?: boolean | null;
    /**
     * Allow clients to create portfolio.
     */
    create?: boolean | null;
    /**
     * Allow clients to update portfolio.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete portfolio.
     */
    delete?: boolean | null;
  };
  films?: {
    /**
     * Allow clients to find films.
     */
    find?: boolean | null;
    /**
     * Allow clients to create films.
     */
    create?: boolean | null;
    /**
     * Allow clients to update films.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete films.
     */
    delete?: boolean | null;
  };
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete services.
     */
    delete?: boolean | null;
  };
  testimonials?: {
    /**
     * Allow clients to find testimonials.
     */
    find?: boolean | null;
    /**
     * Allow clients to create testimonials.
     */
    create?: boolean | null;
    /**
     * Allow clients to update testimonials.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete testimonials.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
    /**
     * Allow clients to create users.
     */
    create?: boolean | null;
    /**
     * Allow clients to update users.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete users.
     */
    delete?: boolean | null;
  };
  studioSettings?: {
    /**
     * Allow clients to find studio-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update studio-settings global.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'portfolio';
        value: string | Portfolio;
      } | null)
    | ({
        relationTo: 'films';
        value: string | Film;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'albums';
        value: string | Album;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'files';
        value: string | File;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  image?: T;
  imageUrl?: T;
  location?: T;
  client?: T;
  featured?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films_select".
 */
export interface FilmsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  videoUrl?: T;
  posterImage?: T;
  posterUrl?: T;
  duration?: T;
  featured?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  serviceNumber?: T;
  tagline?: T;
  shortDescription?: T;
  heroImage?: T;
  heroImageUrl?: T;
  overview?: T;
  targetAudience?: T;
  confidentialityNotice?: T;
  deliverables?:
    | T
    | {
        title?: T;
        description?: T;
        highlight?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  icon?: T;
  featured?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  roleOrEvent?: T;
  quote?: T;
  rating?: T;
  avatar?: T;
  avatarUrl?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  isPrivate?: T;
  fileCategory?: T;
  uploadedFrom?: T;
  uploadedBy?: T;
  title?: T;
  description?: T;
  fiscalYear?: T;
  expiryDate?: T;
  relatedTrackingCode?: T;
  isVerified?: T;
  verifiedBy?: T;
  verificationNotes?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    image?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        splitLayout?: T;
        videoUrl?: T;
        videoPoster?: T;
        storyQuote?: T;
        storyAuthor?: T;
        storyAuthorTitle?: T;
        storyAuthorImage?: T;
      };
  layout?:
    | T
    | {
        studioHero?: T | StudioHeroBlockSelect<T>;
        studioPageHeader?:
          | T
          | {
              breadcrumb?: T;
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        studioMarquee?: T | StudioMarqueeBlockSelect<T>;
        studioPortfolio?: T | StudioPortfolioBlockSelect<T>;
        studioFilms?: T | StudioFilmsBlockSelect<T>;
        studioServices?: T | StudioServicesBlockSelect<T>;
        studioStory?: T | StudioStoryBlockSelect<T>;
        studioStats?: T | StudioStatsBlockSelect<T>;
        studioPillars?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              items?:
                | T
                | {
                    title?: T;
                    desc?: T;
                    iconType?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        studioProcess?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    tag?: T;
                    title?: T;
                    description?: T;
                    iconType?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        studioJournal?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        studioFAQ?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        studioTestimonials?: T | StudioTestimonialsBlockSelect<T>;
        studioSocial?: T | StudioSocialBlockSelect<T>;
        studioBanner?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        studioContact?: T | StudioContactBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        brandMarquee?: T | BrandMarqueeBlockSelect<T>;
        carouselBlock?: T | CarouselBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        aboutUs?: T | AboutUsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioHeroBlock_select".
 */
export interface StudioHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headlinePart1?: T;
  headlinePart2?: T;
  subheadline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioMarqueeBlock_select".
 */
export interface StudioMarqueeBlockSelect<T extends boolean = true> {
  overrideItems?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioPortfolioBlock_select".
 */
export interface StudioPortfolioBlockSelect<T extends boolean = true> {
  isHomepagePreview?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioFilmsBlock_select".
 */
export interface StudioFilmsBlockSelect<T extends boolean = true> {
  isHomepagePreview?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioServicesBlock_select".
 */
export interface StudioServicesBlockSelect<T extends boolean = true> {
  isHomepagePreview?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioStoryBlock_select".
 */
export interface StudioStoryBlockSelect<T extends boolean = true> {
  headline?: T;
  quote?: T;
  paragraph1?: T;
  paragraph2?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioStatsBlock_select".
 */
export interface StudioStatsBlockSelect<T extends boolean = true> {
  overrideStats?: T;
  projectsCount?: T;
  clientsCount?: T;
  socialReach?: T;
  yearsExperience?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioTestimonialsBlock_select".
 */
export interface StudioTestimonialsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioSocialBlock_select".
 */
export interface StudioSocialBlockSelect<T extends boolean = true> {
  instagramHandle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudioContactBlock_select".
 */
export interface StudioContactBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              image?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              image?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  caption?: T;
  columns?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandMarqueeBlock_select".
 */
export interface BrandMarqueeBlockSelect<T extends boolean = true> {
  title?: T;
  brands?:
    | T
    | {
        name?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        link?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
            };
        id?: T;
      };
  height?: T;
  aspectRatio?: T;
  loop?: T;
  autoplay?: T;
  autoplayDelay?: T;
  showArrows?: T;
  showDots?: T;
  showOverlay?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  testimonials?:
    | T
    | {
        type?: T;
        quote?: T;
        authorName?: T;
        authorTitle?: T;
        authorImage?: T;
        location?: T;
        featuredImage?: T;
        videoUrl?: T;
        id?: T;
      };
  layout?: T;
  showTypeFilter?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  layout?: T;
  offices?:
    | T
    | {
        country?: T;
        address?: T;
        phone?: T;
        email?: T;
        officeHours?: T;
        mapUrl?: T;
        flag?: T;
        id?: T;
      };
  formSettings?:
    | T
    | {
        showForm?: T;
        formTitle?: T;
        submitButtonText?: T;
        successMessage?: T;
        recipientEmail?: T;
        fields?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsBlock_select".
 */
export interface AboutUsBlockSelect<T extends boolean = true> {
  isVisibleOnHomepage?: T;
  title?: T;
  content?: T;
  historyTitle?: T;
  historyTimeline?:
    | T
    | {
        year?: T;
        description?: T;
        id?: T;
      };
  showFacebookIframe?: T;
  facebookPageUrl?: T;
  iframePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  displayOrder?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  portfolio?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  films?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  testimonials?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  users?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  studioSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-settings".
 */
export interface StudioSetting {
  id: string;
  hero?: {
    eyebrow?: string | null;
    headlinePart1?: string | null;
    headlinePart2?: string | null;
    subheadline?: string | null;
  };
  marqueeItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?: {
    projectsCount?: number | null;
    clientsCount?: number | null;
    socialReach?: string | null;
    yearsExperience?: number | null;
  };
  story?: {
    headline?: string | null;
    quote?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
  };
  contact?: {
    phone?: string | null;
    whatsappNumber?: string | null;
    email?: string | null;
    address?: string | null;
  };
  socialHandles?: {
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    facebook?: string | null;
  };
  navigation?: {
    navItems?:
      | {
          label: string;
          href: string;
          badge?: string | null;
          submenu?:
            | {
                label: string;
                href: string;
                description?: string | null;
                badge?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ctaButton?: {
      label?: string | null;
      href?: string | null;
    };
    enableSearch?: boolean | null;
    enableWhatsApp?: boolean | null;
    enableLocaleSwitcher?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  contactDetails: {
    phone: string;
    email: string;
    address: string;
    /**
     * Format: Country code followed by number, no spaces or + (e.g., 9779800000000)
     */
    whatsappNumber: string;
    businessHours?:
      | {
          days: string;
          hours: string;
          id?: string | null;
        }[]
      | null;
  };
  officeLocation: {
    latitude: number;
    longitude: number;
  };
  /**
   * Configure Tawk.to Chatbot Widget
   */
  tawkToChat?: {
    enableTawkTo?: boolean | null;
    /**
     * Property ID from your Tawk.to dashboard
     */
    propertyId?: string | null;
    /**
     * Widget ID (defaults to 'default')
     */
    widgetId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-settings_select".
 */
export interface StudioSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headlinePart1?: T;
        headlinePart2?: T;
        subheadline?: T;
      };
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        projectsCount?: T;
        clientsCount?: T;
        socialReach?: T;
        yearsExperience?: T;
      };
  story?:
    | T
    | {
        headline?: T;
        quote?: T;
        paragraph1?: T;
        paragraph2?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsappNumber?: T;
        email?: T;
        address?: T;
      };
  socialHandles?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        facebook?: T;
      };
  navigation?:
    | T
    | {
        navItems?:
          | T
          | {
              label?: T;
              href?: T;
              badge?: T;
              submenu?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    badge?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        enableSearch?: T;
        enableWhatsApp?: T;
        enableLocaleSwitcher?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactDetails?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        whatsappNumber?: T;
        businessHours?:
          | T
          | {
              days?: T;
              hours?: T;
              id?: T;
            };
      };
  officeLocation?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  tawkToChat?:
    | T
    | {
        enableTawkTo?: T;
        propertyId?: T;
        widgetId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  platform: 'youtube' | 'vimeo' | 'custom';
  /**
   * YouTube/Vimeo video ID or full embed URL for custom
   */
  videoId: string;
  caption?: string | null;
  aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quoteText: string;
  attribution?: string | null;
  attributionTitle?: string | null;
  image?: (string | null) | Media;
  style?: ('default' | 'highlight' | 'minimal') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsListBlock".
 */
export interface StatsListBlock {
  heading?: string | null;
  description?: string | null;
  stats?:
    | {
        /**
         * e.g. 500+, 98%, 24/7
         */
        value: string;
        /**
         * e.g. Patients Served, Success Rate
         */
        label: string;
        description?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  columns?: ('2' | '3' | '4') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  heading?: string | null;
  items?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  defaultOpen?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoTableBlock".
 */
export interface InfoTableBlock {
  heading?: string | null;
  caption?: string | null;
  /**
   * Define the columns of the table
   */
  headers?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        cells?:
          | {
              value: string;
              isHeader?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  style?: ('striped' | 'bordered' | 'clean') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}